spring.application.name=backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_creator_studio
spring.datasource.username=postgres
spring.datasource.password=Premi@2003

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true